on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set the correct Node version using nvm
              shell: bash -l {0}
              run: nvm install
            - run: npm ci
            - run: npm test
